rawdata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
filterdata <- subset(rawdata,Date %in% c("1/2/2007","2/2/2007"))
library(reshape2)
reshapedata <- melt(filterdata,id=c("Date","Time"),measure.vars=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
x <- as.POSIXlt(paste(reshapedata$Date, reshapedata$Time), format="%d/%m/%Y %H:%M:%S")
y <- reshapedata$value
par(mar=c(2,4,2,2))
with(reshapedata,plot(x,value, type ="l",xlab="",ylab="Energy sub metering",main=""))
with(subset(reshapedata,variable == "Sub_metering_1"),lines(x,y,col="black"))
with(subset(reshapedata,variable == "Sub_metering_2"),lines(x,y,col="red"))
with(subset(reshapedata,variable == "Sub_metering_3"),lines(x,y,col="blue"))
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot2.png",width = 480, height = 480)
dev.off()